registryCenter:
  url: http://localhost:8700/eureka
  cluster:
    url: http://localhost:8701/eureka,http://localhost:8702/eureka

management:
    endpoints:
        web:
          exposure:
            include: "*"
          cors:
            allowed-origins: "*"
            allowed-methods: "*"

spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
  sleuth:
    sampler:
      probability: 1.0
    traceId128: true
  zipkin:
    sender:
      type: web

test:
  cloud:
    bus:
      enable: true