server:
  port: 8720

#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh
#spring:
#  cloud:
#    bus:
#      enabled: true
#      trace:
#        enabled: true
#  rabbitmq:
#    host: localhost
#    password: guest
#    port: 5672
#    username: guest
