server:
    port: 8710

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/

management:
    endpoints:
        web:
          exposure:
            include: "*"
          cors:
            allowed-origins: "*"
            allowed-methods: "*"
