server:
  port: 8750

turbine:
  app-config: provider,consumer-ribbon,consumer-feign
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream
